[package]
name = "cio-api"
description = "Helper functions and types for doing the activities of a CIO"
version = "0.2.0"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/cio"
documentation = "https://docs.rs/cio-api"

[dependencies]
acme-lib = "^0.8.0"
airtable-api = "^0.1.20"
async-trait = "^0.1.0"
base64 = "0.12"
diffy = "^0.2.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.0.11"
clap = {version = "2", features = ["yaml"]}
# One day go back to the non-forked "cloudflare" lib
cloudflare-rs = "^0.6.0"
csv = "1.1"
comrak = "0.8"
diesel = { version = "1.4.5", features = ["serde_json", "postgres", "chrono", "128-column-tables", "r2d2"] }
#dropshot = "^0.3.0"
dropshot = { git = "https://github.com/jessfraz/dropshot", branch = "working" }
futures-util = "0.3"
google-drive = "^0.1.0"
gsuite-api = "^0.1.10"
#gsuite-api = { path = "../gsuite" }
gusto-api = "^0.1.1"
#gusto-api = { path = "../gusto" }
handlebars = "3"
html2text = "0.1"
#hubcaps = { version = "0.6", features = ["httpcache"] }
hubcaps = { git = "https://github.com/jessfraz/hubcaps", branch = "actions", features = ["httpcache"] }
hyper = "0.13.0"
macros = { path = "../macros" }
nom_pem = "4"
openapiv3 = "0.3.0"
openssl = "0.10"
opentelemetry = { version = "0.10", default-features = false, features = ["trace", "tokio"] }
opentelemetry-zipkin = { version = "^0.8", features = ["reqwest-client"], default-features = false }
pandoc = "0.8"
phonenumber = "0.2"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
revai = { version = "0.1.0" }
schemars = { version = "0.8", features = ["chrono", "uuid"] }
sendgrid-api = "^0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.7"
sheets = "^0.1.0"
shippo = "^0.1.12"
#shippo = { path = "../shippo" }
slack-chat-api = "^0.1.4"
#slack-chat-api = { path = "../slack" }
tailscale-api = "^0.1.0"
#tailscale-api = { path = "../tailscale" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml = "0.5"
tracing = "^0.1"
tracing-attributes = "^0.1"
tracing-futures = "^0.2"
tracing-opentelemetry = "^0.9.0"
tracing-subscriber = { version = "^0.2", features = ["ansi", "fmt", "json", "chrono", "registry"] }
yup-oauth2 = "5"
zip = "0.5"
